twig:
    file_name_pattern: '*.twig'

when@dev:
    twig:
        debug: true
        strict_variables: true
        auto_reload: true
        cache: false

when@test:
    twig:
        strict_variables: true
        auto_reload: true
